language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3.5
  - DJANGO_VERSION=1.4.3
install:
  - pip install -q --use-mirrors Django==$DJANGO_VERSION pep8
  - pip install -q . --use-mirrors
  - pip install -q -r tests/requirements/base.txt
script: python run_tests.py --settings=tests.default
after_script:
    - pep8 --exclude=scheduler,locations,ajax --filename=tests.py,urls.py --ignore=E128 ./rapidsms/
    - pep8 --exclude=scheduler,locations,ajax,urls.py,tests.py ./rapidsms/
notifications:
  irc:
    - "irc.freenode.org#rapidsms"
